// Auto-generated by generate-gallery-images-list.cjs
export const galleryImages: Record<string, string[]> = {
  "wcs": [
    "/images/gallery/wcs/wcs-add-a-move.png",
    "/images/gallery/wcs/wcs-add-move.png",
    "/images/gallery/wcs/wcs-edit-steps.png",
    "/images/gallery/wcs/wcs-home.png",
    "/images/gallery/wcs/wcs-move-description.png",
    "/images/gallery/wcs/wcs-step-details.png"
  ]
};
